name: Quality ensurance
run-name: Execute quality assurance script
on: [push]
jobs:
  qa:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: install poetry
        run: pip install poetry
      - name: install shellcheck
        run: sudo apt-get -qy update && sudo apt-get -qy install shellcheck
      - name: setup project
        run: poetry install
      - name: run quality assurance
        run: bash -euo pipefail ./quality_assurance.sh
